#!/usr/bin/env python2
# Test build of NowPlaying

import struct
import sys

# File where song name is saved
fileName = ".nowPlaying"

def Main():
  f = open(fileName, "w")
  while 1:
    # Read the message length (first 4 bytes).
    text_length_bytes = sys.stdin.read(4)

    # Unpack message length as 4 byte integer.
    text_length = struct.unpack('i', text_length_bytes)[0]

    # Read the text of the message.
    text = sys.stdin.read(text_length)

    # Write to the file and strip quotes.
    f.write(text.strip('"'))
  f.close()
  sys.exit(0)

if __name__ == '__main__':
  Main()
